#!/usr/bin/env python3
"""Run source-release integrity, portability, and link checks."""

from __future__ import annotations

import ast
import csv
import hashlib
import json
import re
import sys
from pathlib import Path
from urllib.parse import unquote


ROOT = Path(__file__).resolve().parents[1]
TEXT_SUFFIXES = {".py", ".sh", ".md", ".json", ".csv", ".txt", ".ipynb", ".cff"}
EXCLUDED_PARTS = {".git", "tmp", "__pycache__"}
FORBIDDEN = tuple(
    "".join(parts)
    for parts in (
        ("/home/", "tweak"),
        ("/mnt/c/", "Users/"),
        ("C:", "\\Users\\"),
        ("C:/", "Users/"),
        ("C:", "\\Kaggle"),
        ("C:/", "Kaggle"),
    )
)
MARKDOWN_LINK = re.compile(r"(?<!!)\[[^\]]+\]\(([^)]+)\)")


def release_files() -> list[Path]:
    return [
        path
        for path in ROOT.rglob("*")
        if path.is_file() and not EXCLUDED_PARTS.intersection(path.relative_to(ROOT).parts)
    ]


def check_local_links(path: Path, text: str, errors: list[str]) -> None:
    for raw_target in MARKDOWN_LINK.findall(text):
        target = raw_target.strip().strip("<>")
        if not target or target.startswith(("#", "http://", "https://", "mailto:")):
            continue
        target = unquote(target.split("#", 1)[0])
        resolved = (path.parent / target).resolve()
        try:
            resolved.relative_to(ROOT)
        except ValueError:
            errors.append(f"link escapes repository in {path.relative_to(ROOT)}: {raw_target}")
            continue
        if not resolved.exists():
            errors.append(f"broken local link in {path.relative_to(ROOT)}: {raw_target}")


def check_checksums(errors: list[str]) -> None:
    manifest = ROOT / "SHA256SUMS.csv"
    if not manifest.is_file():
        errors.append("missing required file: SHA256SUMS.csv")
        return
    with manifest.open(newline="", encoding="utf-8-sig") as stream:
        rows = list(csv.DictReader(stream))
    for row in rows:
        relative = row.get("path", "")
        expected = row.get("sha256", "").lower()
        target = ROOT / relative
        if not target.is_file():
            errors.append(f"checksum target missing: {relative}")
            continue
        actual = hashlib.sha256(target.read_bytes()).hexdigest()
        if actual != expected:
            errors.append(f"checksum mismatch: {relative}")


def main() -> int:
    errors: list[str] = []
    files = release_files()
    for path in files:
        if path.suffix.lower() not in TEXT_SUFFIXES:
            continue
        text = path.read_text(encoding="utf-8-sig")
        for value in FORBIDDEN:
            if value in text:
                errors.append(f"machine-specific path in {path.relative_to(ROOT)}: {value}")
        if path.suffix in {".json", ".ipynb"}:
            try:
                json.loads(text)
            except Exception as exc:
                errors.append(f"invalid JSON in {path.relative_to(ROOT)}: {exc}")
        if path.suffix == ".py":
            try:
                ast.parse(text, filename=str(path))
            except SyntaxError as exc:
                errors.append(f"invalid Python in {path.relative_to(ROOT)}: {exc}")
        if path.suffix == ".md":
            check_local_links(path, text, errors)

    bytecode = [
        path for path in ROOT.rglob("*")
        if path.is_file() and (path.suffix == ".pyc" or "__pycache__" in path.parts)
    ]
    errors.extend(f"generated bytecode present: {path.relative_to(ROOT)}" for path in bytecode)

    required = (
        "README.md",
        "LICENSE",
        "NOTICE",
        "THIRD_PARTY_NOTICES.md",
        "AUTHORS.md",
        "CITATION.cff",
        "CONTRIBUTING.md",
        "TRAINING_AND_GRAPH_PROVENANCE.md",
        "VALIDATION.md",
        "docs/TRAINING_GUIDE.md",
        "docs/DATA_LAYOUT.md",
        "docs/REPRODUCIBILITY_NOTES.md",
        "docs/PUBLICATION_CHECKLIST.md",
        "docs/REPOSITORY_HISTORY.md",
        "docs/biohub_production_957_full_technical_architecture.pdf",
        "production/fork-of-fork-of-division-focused.ipynb",
    )
    for relative in required:
        if not (ROOT / relative).is_file():
            errors.append(f"missing required file: {relative}")

    check_checksums(errors)

    if errors:
        print("Repository verification failed:")
        for error in errors:
            print(f"- {error}")
        return 1
    print(f"Repository verification passed: {len(files)} files checked")
    return 0


if __name__ == "__main__":
    sys.exit(main())
